Remove hardcoded creds
TransformerOptimus/SuperAGI pull request #1136
Opened 2023-08-28 10:29 UTC by Fluder-Paradyne

### Description

### Related Issues

### Solution and Design

### Test Plan

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update

### Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have read the contributing guide and my code conforms to the guidelines.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have added the required tests.

2023-08-28 10:36 UTC, Tarraann submitted a review, later dismissed
Also make change database_url to db_host for run_migrations_offline function

2023-08-30 07:19 UTC, luciferlinx101 approved these changes

2023-08-30 07:21 UTC, luciferlinx101 approved these changes

2023-08-30 07:21 UTC, luciferlinx101 requested changes
Tests are failing

2023-08-31 06:48 UTC, closed without merging