models changes
TransformerOptimus/SuperAGI pull request #1207
Opened 2023-09-07 08:00 UTC by jedan2506

### Description

### Related Issues

### Solution and Design

### Test Plan

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update

### Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have read the contributing guide and my code conforms to the guidelines.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have added the required tests.

2023-09-08 05:53 UTC, luciferlinx101 approved these changes

2023-09-08 05:53 UTC, luciferlinx101 commented on gui/pages/Content/APM/ApmDashboard.js
>                                   src={returnToolkitIcon(tool.toolkit)} alt="tool-icon"/>
Unit Tests are failing please check

2023-09-08 05:54 UTC, luciferlinx101 requested changes
Unit Test fix needed

2023-09-08 06:02 UTC, nborthy approved these changes

2023-09-11 05:28 UTC, luciferlinx101 approved these changes

2023-09-11 05:29 UTC, merged