Benchmark integration main
TransformerOptimus/SuperAGI pull request #1220
Opened 2023-09-11 06:30 UTC by Fluder-Paradyne

### Description

Changes to integrate with agbenchmark

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update

### Checklist
- [x] My pull request is atomic and focuses on a single change.
- [ ] I have read the contributing guide and my code conforms to the guidelines.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have added the required tests.

2023-09-11 06:45 UTC, TransformerOptimus commented on agbenchmark/benchmarks.py
> +    print(config, 'configerino')
remove prints

2023-09-11 06:47 UTC, TransformerOptimus commented on requirements.txt
> +fastapi==0.100.0
do we need this?

2023-09-11 06:47 UTC, TransformerOptimus commented on superagi/agent/agent_iteration_step_handler.py
> +        start = time.perf_counter()
remove perf timer code

2023-09-12 08:01 UTC, luciferlinx101 requested changes

2023-09-12 08:02 UTC, luciferlinx101 commented
Unit Tests are failing too, please check for it

2023-09-12 08:08 UTC, Fluder-Paradyne commented on superagi/helper/resource_helper.py
> +
this fucntion takes output folder as priority instead of get_agent_read_resource_path

2023-09-13 06:23 UTC, luciferlinx101 commented on superagi/controllers/api/agent.py
>          "goal": agent_with_config.goal,
@Maverick-F35 we need unit tests here can you please add?

2023-09-13 06:32 UTC, luciferlinx101 commented on superagi/tools/code/coding_toolkit.py
> +        return [CodingTool(), WriteSpecTool(), WriteTestTool(), ImproveCodeTool(), RunCodeTool()]
Needs to be handled during deployment!

2023-09-21 05:05 UTC, closed without merging