Readme update
TransformerOptimus/SuperAGI pull request #1312
Opened 2023-10-05 12:53 UTC by coder5492

### Description
Updated readme

### Related Issues
None

### Solution and Design
Added 3 new sections (what are we, resources, need help)
Removed unwanted sections
Rearranged few sections

### Test Plan
NA

### Type of change
Readme

2023-10-05 12:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TransformerOptimus/SuperAGI?pullRequest=1312) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/TransformerOptimus/SuperAGI?pullRequest=1312) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Sangeeth Mukundan<br/>:x: coder5492<br/><hr/>**Sangeeth Mukundan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TransformerOptimus/SuperAGI?pullRequest=1312) it.</sub>

2023-10-06 07:02 UTC, Pranay105 requested changes

2023-10-06 07:02 UTC, Pranay105 commented on README.MD
> +Join our vibrant [Discord community](https://discord.gg/YRUmuRMd) for support and discussions.
```suggestion
Join our [Discord community](https://discord.gg/YRUmuRMd) for support and discussions.
```

2023-10-06 07:02 UTC, Pranay105 commented on README.MD
> +This project is under active development and may still have issues. We appreciate your understanding and patience. If you encounter any problems, please first check the open issues. If your issue is
```suggestion
This project is under active development and may still have issues. We appreciate your understanding and patience. If you encounter any problems, please check the open issues first. If your issue is not listed, kindly create a new issue detailing the error or problem you experienced. Thank you for your support!
```

2023-10-09 08:17 UTC, luciferlinx101 approved these changes

2023-10-09 08:19 UTC, Pranay105 approved these changes

2023-10-09 08:19 UTC, merged