Toolkit update
TransformerOptimus/SuperAGI pull request #937
Opened 2023-08-01 10:54 UTC by luciferlinx101

### Description

Prod only feature, any toolkit which is already installed and if there is change in toolkit in marketplace then now once can update their tool.

### Related Issues

### Solution and Design

### Test Plan

Improve Code tool can be now added to user which dont have that since it is already in marketplace

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update

### Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have read the contributing guide and my code conforms to the guidelines.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have added the required tests.

2023-08-02 12:53 UTC, boundless-asura requested changes

2023-08-02 12:53 UTC, boundless-asura commented on gui/pages/api/DashboardService.js
> +
same endpoint with different functions

2023-08-03 06:18 UTC, namansleeps2 commented on gui/pages/api/DashboardService.js
> +
fix kar diya hai, approve krdo bhai

2023-08-03 09:14 UTC, boundless-asura approved these changes

2023-08-03 10:36 UTC, merged